version: "3"

services:
  opensearch:
    image: public.ecr.aws/opensearchproject/opensearch:1.3.6
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      "discovery.type": single-node
      DISABLE_INSTALL_DEMO_CONFIG: true
      DISABLE_SECURITY_PLUGIN: true

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.6
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'

volumes:
  opensearch-data:
